### ISSUE TITLE
adminer official upgrade to 4.16.0

### ISSUE THREAD

**Issue by luomoxu** [TimWolla/docker-adminer#178]
adminer official upgrade to 4.16.0
Hopefully, it can be updated synchronously

**Comment by csrakowski** [comment]
There already was a PR merged to pick up this update: https://github.com/TimWolla/docker-adminer/pull/176

**Comment by TimWolla** [comment]
Indeed, #176 updated the image. Unfortunately Adminer still isn't cleanly compatible with even PHP 8.0, which prevents me from updating the official image builds (since PHP 7.4 is no longer supported).

![Image](https://github.com/user-attachments/assets/8c3e2944-4409-4a19-b487-f51ca21dac30)

**Comment by TimWolla** [comment]
The issue I was seeing above is already fixed with vrana/adminer@b7b22486b2b963153f1ed0d5b4248a53caebda05.

**Comment by GuySartorelli** [comment]
This issue has been closed (as a duplicate, but a duplicate of what?), but the official image still isn't updated - it's unclear what the state of this is, e.g
1. Not doing
2. Done and in the process of updating the official image (with an ETA preferably?)
3. ?? Some other status?

If there's something still blocking the official image from being updated, could we please have an issue open to track that?

**Comment by GuySartorelli** [comment]
Thank you!
